# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - on-poc-hello-wa-01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      # build frontend client
      - name: Build with dotnet
        working-directory: ${{ github.workspace }}/NorskOffshoreAuthenticateClient
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: ${{ github.workspace }}/NorskOffshoreAuthenticateClient
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/onclient

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: onclient
          working-directory: ${{ github.workspace }}/NorskOffshoreAuthenticateClient
          path: ${{env.DOTNET_ROOT}}/onclient
      
      # build backend API service
      - name: Build with dotnet
        working-directory: ${{ github.workspace }}/NorskOffshoreAuthenticateBackend
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: ${{ github.workspace }}/NorskOffshoreAuthenticateBackend
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/onservice

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: onservice
          working-directory: ${{ github.workspace }}/NorskOffshoreAuthenticateBackend
          path: ${{env.DOTNET_ROOT}}/onservice

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: onclient

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'on-poc-hello-wa-01'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AF6D0AF4FE264CB8A49A73400BB3E867 }}
          package: .

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: onservice

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'on-poc-hello-wa-02'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_9cf7fb2107464ff9bfd405e12b7a3b11 }}
          package: .
